import { Business, Discount } from '@/types';

export const mockBusinesses: Business[] = [
  {
    id: '1',
    name: 'Sky Bar Bangkok',
    description: 'Stunning city views with craft cocktails and gourmet bites on the 63rd floor',
    image: 'https://images.pexels.com/photos/1581384/pexels-photo-1581384.jpeg',
    location: {
      latitude: 13.7217,
      longitude: 100.5154,
      address: '1055 Silom Road, Bang Rak, Bangkok 10500',
    },
    category: 'Bar & Restaurant',
    rating: 4.8,
    currentDiscount: {
      id: 'd1',
      businessId: '1',
      title: 'Sunset Happy Hour',
      description: '30% off all drinks and appetizers during sunset',
      percentage: 30,
      validFrom: '17:00',
      validTo: '19:00',
      isActive: true,
    },
    isActive: true,
  },
  {
    id: '2',
    name: 'Gaggan Progressive Indian',
    description: 'Award-winning progressive Indian cuisine with innovative molecular gastronomy',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    location: {
      latitude: 13.7390,
      longitude: 100.5610,
      address: '68/1 Soi Langsuan, Ploenchit Road, Lumpini, Pathumwan, Bangkok 10330',
    },
    category: 'Restaurant',
    rating: 4.9,
    currentDiscount: {
      id: 'd2',
      businessId: '2',
      title: 'Lunch Tasting Menu',
      description: '25% off lunch tasting menu',
      percentage: 25,
      validFrom: '12:00',
      validTo: '15:00',
      isActive: true,
    },
    isActive: true,
  },
  {
    id: '3',
    name: 'Dean & DeLuca Cafe',
    description: 'Premium coffee and gourmet food in an elegant setting with WiFi',
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
    location: {
      latitude: 13.7308,
      longitude: 100.5418,
      address: '399 Sukhumvit Road, Khlong Toei Nuea, Watthana, Bangkok 10110',
    },
    category: 'Cafe',
    rating: 4.7,
    currentDiscount: {
      id: 'd3',
      businessId: '3',
      title: 'Morning Coffee Special',
      description: '20% off coffee and pastries before 11 AM',
      percentage: 20,
      validFrom: '07:00',
      validTo: '11:00',
      isActive: true,
    },
    isActive: true,
  },
  {
    id: '4',
    name: 'Chatuchak Weekend Market',
    description: 'Famous weekend market with authentic Thai street food and local specialties',
    image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg',
    location: {
      latitude: 13.7998,
      longitude: 100.5501,
      address: '587 Kamphaeng Phet 2 Road, Chatuchak, Bangkok 10900',
    },
    category: 'Street Food',
    rating: 4.5,
    currentDiscount: {
      id: 'd4',
      businessId: '4',
      title: 'Weekend Food Special',
      description: '15% off when you buy from 3 different stalls',
      percentage: 15,
      validFrom: '10:00',
      validTo: '18:00',
      isActive: true,
    },
    isActive: true,
  },
  {
    id: '5',
    name: 'Health Land Spa',
    description: 'Traditional Thai massage and wellness treatments in a tranquil setting',
    image: 'https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg',
    location: {
      latitude: 13.7240,
      longitude: 100.5280,
      address: '120 North Sathorn Road, Silom, Bang Rak, Bangkok 10500',
    },
    category: 'Spa & Wellness',
    rating: 4.9,
    currentDiscount: {
      id: 'd5',
      businessId: '5',
      title: 'Afternoon Spa Package',
      description: '40% off traditional Thai massage packages',
      percentage: 40,
      validFrom: '14:00',
      validTo: '17:00',
      isActive: true,
    },
    isActive: true,
  },
  {
    id: '6',
    name: 'Wat Pho Thai Massage School',
    description: 'Authentic traditional Thai massage by certified therapists in cultural setting',
    image: 'https://images.pexels.com/photos/3865676/pexels-photo-3865676.jpeg',
    location: {
      latitude: 13.7465,
      longitude: 100.4927,
      address: '2 Sanamchai Road, Phra Nakhon, Bangkok 10200',
    },
    category: 'Massage Parlour',
    rating: 4.8,
    currentDiscount: {
      id: 'd6',
      businessId: '6',
      title: 'Cultural Massage Experience',
      description: '35% off traditional massage sessions',
      percentage: 35,
      validFrom: '09:00',
      validTo: '17:00',
      isActive: true,
    },
    isActive: true,
  },
  {
    id: '7',
    name: 'Divana Virtue Spa',
    description: 'Luxury spa offering holistic wellness treatments and aromatherapy',
    image: 'https://images.pexels.com/photos/3865711/pexels-photo-3865711.jpeg',
    location: {
      latitude: 13.7420,
      longitude: 100.5600,
      address: '7 Sukhumvit Soi 25, Khlong Toei Nuea, Watthana, Bangkok 10110',
    },
    category: 'Spa & Wellness',
    rating: 4.8,
    currentDiscount: {
      id: 'd7',
      businessId: '7',
      title: 'Wellness Retreat Package',
      description: '50% off spa and aromatherapy combo treatments',
      percentage: 50,
      validFrom: '10:00',
      validTo: '16:00',
      isActive: true,
    },
    isActive: true,
  },
  {
    id: '8',
    name: 'Blue Elephant Restaurant',
    description: 'Royal Thai cuisine in an elegant colonial mansion setting',
    image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg',
    location: {
      latitude: 13.7180,
      longitude: 100.5310,
      address: '233 South Sathorn Road, Yan Nawa, Sathorn, Bangkok 10120',
    },
    category: 'Restaurant',
    rating: 4.6,
    currentDiscount: {
      id: 'd8',
      businessId: '8',
      title: 'Royal Thai Set Menu',
      description: '30% off traditional Thai set menus',
      percentage: 30,
      validFrom: '18:00',
      validTo: '21:00',
      isActive: true,
    },
    isActive: true,
  },
];

export const categories = [
  'All',
  'Restaurant',
  'Bar & Restaurant',
  'Cafe',
  'Street Food',
  'Fast Food',
  'Fine Dining',
  'Spa & Wellness',
  'Massage Parlour',
];